export const ALIAS_MAP: Record<string, { name: string; number: number }> = {
  gen: { name: "Genesis", number: 1 },
  ex: { name: "Exodus", number: 2 },
  exo: { name: "Exodus", number: 2 },
  lev: { name: "Leviticus", number: 3 },
  num: { name: "Numbers", number: 4 },
  deut: { name: "Deuteronomy", number: 5 },
  dt: { name: "Deuteronomy", number: 5 },
  josh: { name: "Joshua", number: 6 },
  jos: { name: "Joshua", number: 6 },
  judg: { name: "Judges", number: 7 },
  jdg: { name: "Judges", number: 7 },
  ruth: { name: "Ruth", number: 8 },
  rut: { name: "Ruth", number: 8 },
  "1sam": { name: "1 Samuel", number: 9 },
  "2sam": { name: "2 Samuel", number: 10 },
  "1ki": { name: "1 Kings", number: 11 },
  "2ki": { name: "2 Kings", number: 12 },
  "1chr": { name: "1 Chronicles", number: 13 },
  "2chr": { name: "2 Chronicles", number: 14 },
  ezr: { name: "Ezra", number: 15 },
  neh: { name: "Nehemiah", number: 16 },
  est: { name: "Esther", number: 17 },
  job: { name: "Job", number: 18 },
  ps: { name: "Psalms", number: 19 },
  psa: { name: "Psalms", number: 19 },
  pss: { name: "Psalms", number: 19 },
  prob: { name: "Proverbs", number: 20 },
  prov: { name: "Proverbs", number: 20 },
  prv: { name: "Proverbs", number: 20 },
  ecc: { name: "Ecclesiastes", number: 21 },
  eccl: { name: "Ecclesiastes", number: 21 },
  sol: { name: "Song of Solomon", number: 22 },
  sos: { name: "Song of Solomon", number: 22 },
  isa: { name: "Isaiah", number: 23 },
  jer: { name: "Jeremiah", number: 24 },
  lam: { name: "Lamentations", number: 25 },
  ezek: { name: "Ezekiel", number: 26 },
  ez: { name: "Ezekiel", number: 26 },
  dan: { name: "Daniel", number: 27 },
  hos: { name: "Hosea", number: 28 },
  joel: { name: "Joel", number: 29 },
  amos: { name: "Amos", number: 30 },
  obad: { name: "Obadiah", number: 31 },
  jon: { name: "Jonah", number: 32 },
  mic: { name: "Micah", number: 33 },
  nah: { name: "Nahum", number: 34 },
  hab: { name: "Habakkuk", number: 35 },
  zeph: { name: "Zephaniah", number: 36 },
  hag: { name: "Haggai", number: 37 },
  zech: { name: "Zechariah", number: 38 },
  zec: { name: "Zechariah", number: 38 },
  mal: { name: "Malachi", number: 39 },
  mat: { name: "Matthew", number: 40 },
  matt: { name: "Matthew", number: 40 },
  mk: { name: "Mark", number: 41 },
  mar: { name: "Mark", number: 41 },
  lk: { name: "Luke", number: 42 },
  luk: { name: "Luke", number: 42 },
  jn: { name: "John", number: 43 },
  joh: { name: "John", number: 43 },
  act: { name: "Acts", number: 44 },
  acts: { name: "Acts", number: 44 },
  rom: { name: "Romans", number: 45 },
  "1cor": { name: "1 Corinthians", number: 46 },
  "2cor": { name: "2 Corinthians", number: 47 },
  gal: { name: "Galatians", number: 48 },
  eph: { name: "Ephesians", number: 49 },
  phil: { name: "Philippians", number: 50 },
  php: { name: "Philippians", number: 50 },
  col: { name: "Colossians", number: 51 },
  "1thes": { name: "1 Thessalonians", number: 52 },
  "2thes": { name: "2 Thessalonians", number: 53 },
  "1tim": { name: "1 Timothy", number: 54 },
  "2tim": { name: "2 Timothy", number: 55 },
  tit: { name: "Titus", number: 56 },
  phlm: { name: "Philemon", number: 57 },
  heb: { name: "Hebrews", number: 58 },
  jas: { name: "James", number: 59 },
  "1pet": { name: "1 Peter", number: 60 },
  "2pet": { name: "2 Peter", number: 61 },
  "1jn": { name: "1 John", number: 62 },
  "2jn": { name: "2 John", number: 63 },
  "3jn": { name: "3 John", number: 64 },
  jude: { name: "Jude", number: 65 },
  rev: { name: "Revelation", number: 66 },
  apoc: { name: "Revelation", number: 66 },
};
